# Generated by Django 5.1.2 on 2024-11-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0009_transaction_transaction_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_category',
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=50),
        ),
    ]
