# Generated by Django 5.1.2 on 2024-11-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0016_remove_budget_amount_remove_budget_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='email',
            field=models.EmailField(default='placeholder@example.com', max_length=254),
        ),
    ]
