# Generated by Django 5.1.2 on 2024-11-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=400)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('category', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(choices=[('income', 'Income')], max_length=150)),
            ],
        ),
    ]
