# Generated by Django 5.1.2 on 2024-11-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='profile_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('business', 'Business'), ('family', 'Family')], default='personal', max_length=10),
        ),
    ]
