# Generated by Django 5.1.2 on 2024-11-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_subaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='family',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='personal',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='SubAccount',
        ),
    ]
