# Generated by Django 5.1.2 on 2024-11-02 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_expenses_income_delete_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='total_expenses',
        ),
    ]
