# Generated by Django 5.1.2 on 2024-11-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_remove_expenses_total_expenses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='category',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='category',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='expenses',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
