# Generated by Django 5.1.2 on 2024-11-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_expenses_balance_type_income_balance_type_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='balance_type',
        ),
        migrations.RemoveField(
            model_name='income',
            name='balance_type',
        ),
        migrations.AddField(
            model_name='expenses',
            name='entry_type',
            field=models.CharField(default='fixed', max_length=10),
        ),
        migrations.AddField(
            model_name='income',
            name='entry_type',
            field=models.CharField(default='fixed', max_length=10),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='item',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='income',
            name='item',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
