# Generated by Django 5.1.2 on 2024-11-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
