# Generated by Django 5.1.2 on 2024-11-27 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0011_remove_income_user_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(default='Expense', max_length=10),
        ),
    ]
