# Generated by Django 5.1.2 on 2024-11-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0013_alter_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='unique_hash',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
