# Generated by Django 5.1.2 on 2024-11-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0017_alter_budget_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='profile',
        ),
        migrations.AddField(
            model_name='transaction',
            name='profile_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('business', 'Business'), ('family', 'Family')], default='personal', max_length=10),
        ),
    ]
